# Generated by Django 4.0.2 on 2022-05-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=120, null=True)),
                ('middlename', models.CharField(max_length=120, null=True)),
                ('lastname', models.CharField(max_length=120, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('id_type', models.CharField(max_length=120)),
                ('id_number', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
                ('staff_image', models.ImageField(default='default.jpg', upload_to='staff_pics')),
                ('staff_id', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('emergency_person', models.CharField(max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_address', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='ExecutiveMembers',
        ),
    ]
