# Generated by Django 4.0.2 on 2022-05-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_staff_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
