# Generated by Django 4.0.2 on 2022-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_image',
            field=models.ImageField(upload_to='staff_pics'),
        ),
    ]
