# Generated by Django 4.0.2 on 2022-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_staff_email_staff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='staff',
            name='day',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
