# Generated by Django 4.0.2 on 2022-05-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_staff_date_of_birth_staff_day_staff_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='middlename',
            new_name='middleName',
        ),
    ]
