# Generated by Django 4.0.2 on 2022-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_due_loan_rename_firstname_staff_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='relationship',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
