# Generated by Django 4.0.2 on 2022-07-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_staff_relationship_alter_staff_staff_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Due',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
