# Generated by Django 4.0.2 on 2022-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_members_id_alter_members_gfxnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='declaration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='district',
            field=models.CharField(choices=[('Atwima-Mponua-District', 'Atwima-Mponua District'), ('Adansi South District', 'Adansi South District'), ('Afigya-Kwabre District', 'Afigya-Kwabre District'), ('Ahafo-Ano North District', 'Ahafo-Ano North District'), ('Ahafo-Ano South District', 'Ahafo-Ano South District'), ('Amansie Central District', 'Amansie Central District'), ('Amansie West District', 'Amansie West District'), ('Asante-Akim Central Municipal District', 'Asante-Akim Central Municipal District'), ('Asante-Akim North District', 'Asante-Akim North District'), ('Asante-Akim South District', 'Asante-Akim South District'), ('Asokore-Mampong Municipal District', 'Asokore-Mampong Municipal District'), ('Atwima-Kwanwoma District', 'Atwima-Kwanwoma District'), ('Atwima-Nwabiagya District', 'Atwima-Nwabiagya District'), ('Bekwai Municipal District', 'Bekwai Municipal District'), ('Bosome-Freho District', 'Bosome-Freho District'), ('Bosomtwe District', 'Bosomtwe District'), ('Ejisu-Juaben Municipal District', 'Ejisu-Juaben Municipal District'), ('Ejura-Sekyedumase District', 'Ejura-Sekyedumase District'), ('Kumasi Metropolitan District', 'Kumasi Metropolitan District'), ('Kumawu District', 'Kumawu District'), ('Kwabre East District', 'Kwabre East District'), ('Mampong Municipal District', 'Mampong Municipal District'), ('Obuasi Municipal District', 'Obuasi Municipal District'), ('Offinso Municipal District', 'Offinso Municipal District'), ('Offinso North District', 'Offinso North District'), ('Sekyere-Afram Plains District (map)', 'Sekyere-Afram Plains District (map)'), ('Sekyere East District', 'Sekyere East District'), ('Sekyere South District (map)', 'Sekyere South District (map)'), ('Adansi North District (map)', 'Adansi North District (map)'), ('Berekum East Municipal District', 'Berekum Wast Municipal District'), ('Berekum West Municipal District', 'Berekum West Municipal District'), ('Dormaa East District', 'Dormaa East District'), ('Dormaa Central Municipal District', 'Dormaa Central Municipal District'), ('Dormaa West District', 'Dormaa West District'), ('Jaman North District', 'Jaman North District'), ('Jaman South District', 'Jaman South District'), ('Sunyani Municipal District', 'Sunyani Municipal District'), ('Sunyani West District', 'Sunyani West District'), ('Tain District', 'Tain District'), ('Banda District', 'Banda District'), ('Asunafo South District', 'Asunafo South District'), ('Asutifi District', 'Asutifi District'), ('Asutifi South District', 'Asutifi South District'), ('Atebubu-Amantin District', 'Atebubu-Amantin District'), ('Kintampo North Municipal District', 'Kintampo North Municipal District'), ('Kintampo South District', 'Kintampo South District'), ('Nkoranza North District', 'Nkoranza North District'), ('Nkoranza South Municipal District', 'Nkoranza South Municipal District'), ('Pru District', 'Pru District'), ('Sene East District', 'Sene East District'), ('Sene West District', 'Sene West District'), ('Tano North District', 'Tano North District'), ('Tano South District', 'Tano South District'), ('Techiman Municipal District', 'Techiman Municipal District'), ('Techiman North District', 'Techiman North District'), ('Asunafo North Municipal District', 'Asunafo North Municipal District'), ('Abura - Asebu - Kwamankese District', 'Abura - Asebu - Kwamankese District'), ('Agona West Municipal District', 'Agona West Municipal District'), ('Ajumako-Enyan-Essiam District', 'Ajumako-Enyan-Essiam District'), ('Asikuma - Odoben - Brakwa District', 'Asikuma - Odoben - Brakwa District'), ('Assin North Municipal District', 'Assin North Municipal District'), ('Assin South District', 'Assin South District'), ('Awutu-Senya District', 'Awutu-Senya District'), ('Awutu Senya East Municipal District', 'Awutu Senya East Municipal District'), ('Cape Coast Metropolitan District', 'Cape Coast Metropolitan District'), ('Effutu Municipal District', 'Effutu Municipal District'), ('Ekumfi District', 'Ekumfi District'), ('Gomoa East District', 'Gomoa East District'), ('Gomoa West District', 'Gomoa West District'), ('Komenda-Edina', 'Komenda-Edina'), ('Eguafo-Abrem Municipal District', 'Eguafo-Abrem Municipal District'), ('Mfantseman Municipal District', 'Mfantseman Municipal District'), ('Twifo Atti - Mokwa District', 'Twifo Atti - Mokwa District'), ('Twifo Hemang - Lower Denkyira District', 'Twifo Hemang - Lower Denkyira District'), ('Upper Denkyira East Municipal District', 'Upper Denkyira East Municipal District'), ('Upper Denkyira West District', 'Upper Denkyira West District'), ('Agona East District', 'Agona East District'), ('Aowin District', 'Aowin District'), ('Bia District', 'Bia District'), ('Bia East District', 'Bia East District'), ('Bibiani-Anhwiaso-Bekwai District', 'Bibiani-Anhwiaso-Bekwai District'), ('Bodi District', 'Bodi District'), ('Sefwi-Wiawso District', 'Sefwi-Wiawso District'), ('Yilo Krobo Municipal District', 'Yilo Krobo Municipal District'), ('Suaman District', 'Suaman District'), ('Juaboso District', 'Juaboso District'), ('Sefwi-Akontombra District', 'Sefwi-Akontombra District'), ('Keta', 'Keta'), ('Kpando', 'Kpando'), ('Ho', 'Ho'), ('Kadjebi', 'Kadjebi'), ('South Tongu', 'South Tongu'), ('South Dayi', 'South Dayi'), ('Krachi East', 'Krachi East'), ('Ketu North', 'Ketu North'), ('Nkwanta North', 'Nkwanta North'), ('Biakoye', 'Biakoye'), ('Nkwanta South', 'Nkwanta South'), ('Jasikan', 'Jasikan'), ('North Dayi', 'North Dayi'), ('Central Tongu', 'Central Tongu'), ('Krachi West', 'Krachi West'), ('Afadzato - South', 'Afadzato - South'), ('Agortime Ziope', 'Agortime Ziope'), ('North Tongu', 'North Tongu'), ('Akatsi North', 'Akatsi North'), ('Ho West', 'Ho West'), ('Krachi Ntsumuru', 'Krachi Ntsumuru'), ('Adaklu', 'Adaklu'), ('Akatsi South', 'Akatsi South'), ('>Ketu South', '>Ketu South'), ('Hohoe', 'Hohoe'), ('Atebubu Amantin Municipal', 'Atebubu Amantin Municipal'), ('Kintampo South', 'Kintampo South'), ('Nkoranza North', 'Nkoranza North'), ('Nkoranza South Municipal', 'Nkoranza South Municipal'), ('Pru', 'Pru'), ('Sene East', 'Sene East'), ('Sene West', 'Sene West'), ('Techiman Municipal', 'Techiman Municipal'), ('Techiman North', 'Techiman North'), ('Kintampo Municipal', 'Kintampo Municipal'), ('JASIKAN DISTRICT', 'JASIKAN DISTRICT'), ('KRACHI EAST MUNICIPAL', 'KRACHI EAST MUNICIPAL'), ('BIAKOYE DISTRICT', 'BIAKOYE DISTRICT'), ('KADJEBI DISTRICT', 'KADJEBI DISTRICT'), ('KRACHI NCHUMURU DISTRICT', 'KRACHI NCHUMURU DISTRICT'), ('KRACHI WEST DISTRICT', 'KRACHI WEST DISTRICT'), ('NKWANTA NORTH DISTRICT', 'NKWANTA NORTH DISTRICT'), ('NKWANTA SOUTH MUNICIPAL', 'NKWANTA SOUTH MUNICIPAL'), ('Akwapim North Municipal District', 'Akwapim North Municipal District'), ('Akyemansa District', 'Akyemansa District'), ('Asuogyaman District', 'Asuogyaman District'), ('Atiwa District', 'Atiwa District'), ('Ayensuano District', 'Ayensuano District'), ('Birim Central Municipal District', 'Birim Central Municipal District'), ('Birim North District', 'Birim North District'), ('Birim South District', 'Birim South District'), ('Denkyembour District', 'Denkyembour District'), ('East Akim Municipal District', 'East Akim Municipal District'), ('Fanteakwa District', 'Fanteakwa District'), ('Kwaebibirem District', 'Kwaebibirem District'), ('Kwahu Afram Plains North District', 'Kwahu Afram Plains North District'), ('Kwahu Afram Plains South District', 'Kwahu Afram Plains South District'), ('Kwahu East District', 'Kwahu East District'), ('Kwahu South District', 'Kwahu South District'), ('Kwahu West Municipal District', 'Kwahu West Municipal District'), ('Lower Manya Krobo Municipal District', 'Lower Manya Krobo Municipal District'), ('New Juaben Municipal District', 'New Juaben Municipal District'), ('Nsawam - Adoagyire Municipal District', 'Nsawam - Adoagyire Municipal District'), ('Suhum Municipal District', 'Suhum Municipal District'), ('Upper Manya Krobo District', 'Upper Manya Krobo District'), ('Upper West Akim District', 'Upper West Akim District'), ('West Akim Municipal', 'West Akim Municipal'), ('Akwapim South District', 'Akwapim South District')], max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='education',
            field=models.CharField(choices=[('---------', '---------'), ('Basic Education', 'Basic Education'), ('JHS/JSS', 'JHS/JSS'), ('Middle School Leaving Certificate', 'Middle School Leaving Certificate'), ('High School/Secondary School', 'High School/Secondary School'), ('Tertiary Level', 'Tertiary Level')], max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='familysize',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('---------', '---------'), ('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='idtype',
            field=models.CharField(choices=[('---------', '---------'), ('National ID (Ghana Card)', 'National ID (Ghana Card)'), ('Voters ID', 'Voters ID')], max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='loc_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='loc_longitutde',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='marriage',
            field=models.CharField(choices=[('---------', '---------'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divored'), ('Widow', 'Widow'), ('Widower', 'Widower')], max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='region',
            field=models.CharField(choices=[('Ashanti(Kumasi)', 'Ashanti(Kumasi)'), ('Ahafo(Gaoso)', 'Ahafo(Gaoso)'), ('Bono(Sunyani)', 'Bono(Sunyani)'), ('Western(Takoradi)', 'Western(Takoradi)'), ('Central(Cape Coast)', 'Central(Cape Coast)'), ('Bono East (Techiman)', 'Bono East (Techiman)'), ('Oti(Dambai)', 'Oti(Dambai)'), ('Volta(Ho)', 'Volta(Ho)'), ('Eastern(Koforidua)', 'Eastern(Koforidua)'), ('Western North(Sefwi Wiaso)', 'Western North(Sefwi Wiaso)')], max_length=120),
        ),
        migrations.AlterField(
            model_name='members',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Nana', 'Nana'), ('Ohemaa', 'Ohemaa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='useoffund',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
