# Generated by Django 4.0.2 on 2022-07-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_members_caretaker_remove_members_caretaker2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='members',
            name='namesoffamilymembers',
        ),
        migrations.RemoveField(
            model_name='members',
            name='namesofpeep',
        ),
        migrations.RemoveField(
            model_name='members',
            name='ownersgfx',
        ),
        migrations.RemoveField(
            model_name='members',
            name='startdate',
        ),
        migrations.AddField(
            model_name='members',
            name='crop2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='crop3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='crop4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='crop5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='farmowner2',
            field=models.CharField(blank=True, choices=[('self', 'self'), ('labourer', 'labourer'), ('rented', 'rented/lease'), ('cropsharing', 'crop sharing'), ('family', 'family')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='farmowner3',
            field=models.CharField(blank=True, choices=[('self', 'self'), ('labourer', 'labourer'), ('rented', 'rented/lease'), ('cropsharing', 'crop sharing'), ('family', 'family')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='farmowner4',
            field=models.CharField(blank=True, choices=[('self', 'self'), ('labourer', 'labourer'), ('rented', 'rented/lease'), ('cropsharing', 'crop sharing'), ('family', 'family')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='farmowner5',
            field=models.CharField(blank=True, choices=[('self', 'self'), ('labourer', 'labourer'), ('rented', 'rented/lease'), ('cropsharing', 'crop sharing'), ('family', 'family')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='farmsize2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='farmsize3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='farmsize4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='farmsize5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_latitude2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_latitude3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_latitude4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_latitude5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_longitude2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_longitude3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_longitude4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='loc_longitude5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='location2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='members',
            name='location3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='members',
            name='location4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='members',
            name='location5',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='members',
            name='farmsize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='loc_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='loc_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
