# Generated by Django 4.0.2 on 2022-07-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_members_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='members'),
        ),
    ]
