# Generated by Django 4.0.2 on 2022-07-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_members_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Nana', 'Nana'), ('Ohemaa', 'Ohemaa')], max_length=10)),
                ('firstName', models.CharField(max_length=120, null=True)),
                ('middleName', models.CharField(max_length=120, null=True)),
                ('lastName', models.CharField(max_length=120, null=True)),
                ('day', models.CharField(blank=True, max_length=3)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('id_type', models.CharField(choices=[('National ID (Ghana Card)', 'National ID (Ghana Card)'), ('Voters ID', 'Voters ID')], max_length=120)),
                ('id_number', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('password', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('staff_image', models.ImageField(default='default.jpg', upload_to='staff_pics')),
                ('position', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('emergency_person', models.CharField(max_length=120)),
                ('emergency_phone', models.CharField(max_length=10)),
                ('relationship', models.CharField(blank=True, max_length=120)),
                ('emergency_address', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='gfxnumber',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
