# Generated by Django 4.0.2 on 2022-07-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_staff_password_staff_district_staff_region_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Profile',
        ),
    ]
