# Generated by Django 4.0.1 on 2022-02-12 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_gfx', models.IntegerField()),
                ('region', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('society', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('preferred_name', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
                ('educational_level', models.CharField(max_length=120)),
                ('hometown', models.CharField(max_length=120)),
                ('id_type', models.CharField(max_length=120)),
                ('id_number', models.IntegerField()),
                ('marriage_status', models.CharField(max_length=120)),
                ('spoue_name', models.CharField(max_length=120)),
                ('spouse_occupation', models.CharField(max_length=120)),
                ('spouse_number', models.CharField(max_length=120)),
                ('next_of_kin', models.CharField(max_length=120)),
                ('relationship_kin', models.CharField(max_length=120)),
                ('number_kin', models.CharField(max_length=120)),
                ('Num_partners', models.IntegerField()),
                ('family_size', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('owner_of_farm', models.CharField(max_length=120)),
                ('number_of_labourers', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('name_of_owner', models.CharField(max_length=120)),
                ('owners_gfx', models.CharField(max_length=120)),
                ('how_many_people', models.IntegerField()),
                ('names_of_families', models.TextField()),
                ('crop_cultivated', models.CharField(max_length=120)),
                ('farm_size', models.IntegerField()),
                ('farm_location', models.CharField(max_length=120)),
                ('years_in_farming', models.IntegerField()),
                ('side_business', models.CharField(max_length=120)),
                ('side_business_specify', models.CharField(max_length=120)),
                ('current_side_business', models.CharField(max_length=120)),
                ('current_business_specify', models.CharField(max_length=120)),
                ('average_yield', models.IntegerField()),
                ('previous_yield', models.IntegerField()),
                ('benefit_from_farm', models.CharField(max_length=120)),
                ('buyer_of_produce', models.CharField(max_length=120)),
                ('number_of_times', models.CharField(max_length=120)),
                ('benefit_from_buyer', models.CharField(max_length=120)),
                ('usage_of_funds', models.CharField(max_length=120)),
                ('bank_transacting_with', models.CharField(max_length=120)),
                ('other_specify', models.CharField(max_length=120)),
                ('how_long', models.CharField(max_length=120)),
                ('interes_in_gnacofa', models.CharField(max_length=120)),
                ('specify_why', models.CharField(max_length=120)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
