# Generated by Django 4.0.1 on 2022-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_member_gfx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Num_partners',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='average_yield',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='family_size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='farm_size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='how_many_people',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='member',
            name='number_of_labourers',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='previous_yield',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='years_in_farming',
            field=models.CharField(max_length=30),
        ),
    ]
