# Generated by Django 4.0.1 on 2022-02-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_num_partners_alter_member_average_yield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_gfx',
            field=models.CharField(max_length=10),
        ),
    ]
